language: node_js
node_js:
- 11
env:
  global:
  - secure: Hhu45VPjqdXym5Z6uuuH/M12nLiz8gCKnChdg0EgupB6Zl4JZgKHgckxK/G17UKCLPRxnqKQnQBbgF5pUXFjYavP/5mN6pq6zjBK5sNtKae//BYiBCDnDLmWpmB7y3XYRjdQDQ0PL4iSL4FfK0HjVA4mXsLLC4fGT0rq/GOox9wglU5IukJHiEB8Y2cReIPXoNcaJ6wx7YI0JsI0VME/yalmx41Xgx7NCIojtzV7KO/S1IClKA60RUAErTp3hrJiU3B1lSHx0/TicZ+biaJMJ+mGsQfDHD3W6CEsDbuptAXsdDoYKlwfp+1DSG6KaluKjvsLPAxQKQhi/70NZlWLc/rLnIlX6CT0rIkjfMgXwmd46BLEs0CnGnz814tmKcFADZ7f+y1GVqVYCeu1218MoHewfkLXzPjFEURkI3397s4qeCPC3W2EyWDQwAH41wCz71/NFVCVCew6k1Tg/+xqvOeoY7AQ6AT/dPImYYzCQ+GNysJDCD943BQf8MMwMwqW2K5/7vDeX3hbQZpQTUiKwhZ8E5ULwqREd0JS1oxjatTBt/jiEBOSIr6w9Dr7qI6t95uletV4y0PfhBBU+oSPIfTmOnawCSQvG8Vxtw5UtM/uZ3u5Q+Zuavwp3yA1w3hWFDrt/y2AJvBdOeJRYpz/SiyMC8R3FV3Nj2QeNdizLPs=
  matrix:
    secure: RIHlLTYX61T/oqLHHWO3lnRsX6WBLQK8iO4sh09mCtPuM0rbSTDqYXqkHLwavkvfKxTe+0ktA2SD6viD9djKh96Nl46SpfvoIhAZod3VyiUZKyZ+5Lln3vI2BjjyMR1PYrCrfAO4oHBZucmfau18fO8KhszjidaJ1dsMmvprrlHrbpsZC4IygnuCD7otuvWNaT1Xu197OSSCRsTyjpB5teKyzmkNKrgjiSTW8KUklqIC2Xy8TXsKYh1aqJLX1rZMxPV3d0RGoxp0QBe/yXXZMaZUyJo4BXU1aLZr/byQQzqvn/8GBFQmQ6npkZtExMhMQTn0sJS/YMz0I7AyOTUAhx2J35FR9j/GnoccMAt1JxSZWou+Ug82aLyns0UTZr8jHT5vnxaSJAk7pwQr/SuLkPH+0fIc7bQAMRNhME+9ThE7MzvF1AVombL3KIxKL0TNP3LW5SrF0hmncLtyoHQFuhy5OmHIkw5NcKE+pJhlIczmHmXwOF/P3MrdDksYaNRy/mcRxyOQ670md3Ye4FR4vK5awiPydLZaLOLUDOxkAEdvVGw1LZFtW3ln1iLcMzYdUOp4CkzpwqIa4Z0OIxGxLvdOWbT6VkHuhbof2mHVwBFFUyvHdo98qLlV+v+1y1d0E+fDWMk0IM9XnvoYYHQvngWO7Z2eXse8/NrHlY12nto=
install:
- npm install -g
script: node validate.js
after_success:
- openssl aes-256-cbc -k "$travis_key_password" -d -md sha256 -a -in travis_key.enc
  -out travis_key
- echo "Host github.com" > ~/.ssh/config
- echo "  IdentityFile  $(pwd)/travis_key" >> ~/.ssh/config
- chmod 400 travis_key
- git config user.email "travis@travis.org"
- git config user.name "travis"
- git checkout master
- cp unvalidated_activity_list.jsonld activity-list.jsonld
- git add activity-list.jsonld
- git commit --allow-empty -m "[ci skip] Activity list export validated"
- git push --force git@github.com:openactive/activity-list.git HEAD:master
