language: node_js
node_js:
- 11
env:
  global:
    secure: AUtgubDzsSV3oQd8RgHgjkyvqiaeGThJ/asHsZerXsPIEZttSZOXBvGgODnF8k2hzCIeqj9NfLAfcwI+xCr0aO+kxHHZE2PZLvBAuRGW9fa7nktun6EmG6KZwADQZ6m3CSRXjpoApZegdfsl52Pbb95ULCRXCsvBjE0KThc8ij+k2BDImRJgnr4nummeccS8EWpdQfbhjpx+tOmEnftIWfipvsnXnnmuQjkNTtiIkH2/GMTRI+4D4Zz4et13U6kR+s9dg4WzvY14YCbLxmMf0HG6maHhreMErXOmunubPWTU7AD+tfXybhNxdX3pc13ai1GOeWRyyDmIdOgNEi+Ldwnsa172FfpumWI5nNAHHnmJg1G5AVhr6ggE5pjzvTnfsZtIxTufuW0goJ/PYCL0VG50+jssG5ro4QghrK08GAQStKF6/pr0vxMJzbi32BjuqZLLNyNGbRJHxfHlPovWHrEGZJCheleUHsn4kcpKFzm6GdVGbPQk0Qw7zCTa2xBYODin98qEASrl+08fEIIIPVkA43KpN+kY73fiJb+VttdWOu4Tlo/wzw147qxqWc7eTMQxw/7lEeMTLt0f9G4ouFtfyfchFAF47uO0DCjHzBjcNw46GlZgPmAGyaaSU4TmRA+UqJIvX8X+mDVfLvJA2VFr3vvNXvSi1kO/gs1NglQ=
  matrix:
    secure: bFzFIL3OhIk2ykCJbtlsDyLlZcOn+pL8W2mwR4Gjalbwfj1zjeqyyg9ydPFxqlmrXbibK4Sp2fy+bDlQ0936YzSIl8GYWAJ5RU8Y+gFDS6yWN0BfOn4EyTc3KqMG3iYz+gPZIGcjUAvGCTNWAyIol+g0n04wYlkiiTT5daVxU3Yu8TgZGUs2eDsXAZTcYXMRLGtBAnWpH8lbW3CFhjyiEDZ/sIkEutLgMbpcfId/fO9vJabGsoOj3fYHjKHycJ840TuSfaC7LdFc1vN6QBZuUc0kesdGywJOyz/hNc3uTvCaSGwDXBBFkGZ9pfEsc9jtBXlY7fE5lHWMaw/3YtUc+MxUmyxoTCfObZYR39fD4110LRVcfHF25fllfthuprg85kL8zlRZkx0CzjOyf7ADbfJoFRHhIgDZyT06QdRL+oX32wOrLFfXQaJ2wgmzG8hp2ujbVpEdlgOV29v/eWOSqIDRoLrLaHsSuksdJjpvidWpYPB8+UvUTPXLdvG1NIKl5qkLiRm+AQsiUT4ITrd8lB7zuG4Yy885OlmVZjJLWxl31wcM3VCnMsQieX8SmAT9wl+s0+A55JaO8c6Cc0xycSpn11JMSxZj/8Mnu+IkQSKNjDvVjh7tFQLQTtfwH5Uk6WaoiGnlm646aOEdCGUUIdZoOfUpkeGFLX5nELczX8A=
install:
- npm install -g
script: node validate.js
after_success:
- openssl aes-256-cbc -k "$travis_key_password" -d -md sha256 -a -in travis_key.enc -out travis_key
- git config user.email "travis@travis.org"
- git config user.name "travis"
- git checkout master
- cp unvalidated_activity_list.jsonld validated_activity_list.jsonld
- git add validated_activity_list.jsonld
- git commit --allow-empty -m "[ci skip] Activity list export validated"
- git push --force git@github.com:openactive/activity-list.git HEAD:master
