name: Release

on:
  push:
    branches: [ master, develop ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - id: commit-date
        name: Get latest commit date
        uses: ithaque-renovation/latest-commit-date-action@v1
      
      - name: Render PR body
        id: fetch_pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              head: context.sha
            });
            const pr = pulls.find(pr => pr.merge_commit_sha === context.sha);
            if (pr) {
              return `${pr.body}\n\nAssociated PR: #${pr.number}`;
            } else {
              console.log('No associated PR found; skipping release creation.');
              return null;
            }

      - name: Create Release
        if: "!contains(toJSON(github.event.commits.*.message), '[no-release]') && steps.fetch_pr.outputs.result != null"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.commit-date.outputs.latest-commit-date }}
          release_name: Release v${{ steps.commit-date.outputs.latest-commit-date }}
          body: ${{ steps.fetch_pr.outputs.result }}
          draft: false
          prerelease: false
 